services:
  runner:
    image: ghcr.io/vabalops/gha-lab/runner:latest
    restart: always
    environment:
      - REPO=$REPO
      - TOKEN=$TOKEN
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 500m
        reservations:
          cpus: '0.4'
          memory: 300m
