name: Validate image build
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'runners/**'
jobs:
  prod-pr-check:
    runs-on: self-hosted
    steps:
      - name: Echo message
        run: echo "PR opened or updated against main with changes in runners directory"
