name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: echo "Hello!"
      - name: Print goodbye
        run: echo "Bye!"
